### ISSUE TITLE
CSV 格式的译名标准化列表

### ISSUE THREAD

**Issue by 3TUSK** [Meow-J/Mod-Translation-Styleguide#15]
> 最好还是泛用点的格式，比如Minecraft lang，csv，表格，这样我就能最多两步丢进weblate了
--- exz

【注：exz 最近在搞一个集中式的 mod 翻译平台。】

**Comment by TartaricAcid** [comment]
你是说一些类似于词典一样的东西？用csv格式书写？

**Comment by exzhawk** [comment]
两种可能

1. 写一个csv, 有English,Chinese,Comment之类的字段, 然后用个脚本去生成markdown
2. 把现在的markdown改成表格或者某种固定的类似 English: Chinese (Comment) 的格式, 然后用个脚本去生成csv.

**Comment by Towdium** [comment]
稍微写了个脚本，可以把目前的md文档转化成csv或者md表格
如果有需要的就拿去用吧
https://gist.github.com/Towdium/4778eeccc8e1b8b4ef1a4394d7794ef5
