### ISSUE TITLE
Mod名翻译问题

### ISSUE THREAD

**Issue by Krasjet** [Meow-J/Mod-Translation-Styleguide#2]
目前我的初步方案：
按照以下步骤依次进行：
1. 如果是国产mod，则中文名采用mod作者自定义的名称
2. 如果是经典mod，有早已熟知唯一译名，则采用该熟知译名（如IndustrialCraft2，工业时代2；Twilight Forest，暮色森林）
3. 如果mod名为术语或者单词翻译不存在歧义，则采用翻译名（如Forestry，林业；Logistics Pipes，物流管道；Chisel，凿子）
4. 如以上均不符，则在汉化文件内保留英文，民间翻译仅供流传使用。有一定用户量后，如果某一民间翻译人气非常高，则之后会采用人气最高版本的翻译。（如Minecraft，我的世界）

**Comment by 3TUSK** [comment]
AcademyCraft...

**Comment by Krasjet** [comment]
参见第一条，`itemGroup.AcademyCraft=AcademyCraft`

**Comment by 3TUSK** [comment]
不，我比较在意的是AcademyCraft的通用译名

**Comment by Krasjet** [comment]
可以不翻译啦/w\

**Comment by 3TUSK** [comment]
等等等等，TerraFirmaCraft怎么回事

**Comment by Krasjet** [comment]
不知道/w\

**Comment by 3TUSK** [comment]
但是`群峦传说`这个翻译绝对是意译

**Comment by Krasjet** [comment]
嘛，参考最后一条啦

**Comment by Krasjet** [comment]
并没有说一定要直译或者意译

**Comment by JackyJnirvana** [comment]
是否需要添加一个关于意译的标准？

**Comment by 3TUSK** [comment]
@JackyWangMislantiaJnirvana 意译要是再来标准的话，我们就是汉化工厂了...

**Comment by TartaricAcid** [comment]
那Tough As Nails呢
优酷某知名实况主的翻译是“意志坚定”
╮(￣⊿￣)╭

**Comment by 3TUSK** [comment]
@Meow-J 询问xx如何翻译的是不是应该开独立的issue？
@TartaricAcid _Tough As Nails_这个名字本身是在暗示生存难度...嘛只有时间能说明一切了

**Comment by 3TUSK** [comment]
没人？
