### ISSUE TITLE
手册翻译指南

### ISSUE THREAD

**Issue by 3TUSK** [Meow-J/Mod-Translation-Styleguide#3]
嘛，标题很笼统，下面来（试着）细分一下：
- 手册是否一定与教程画等号？
  - 例子：ChromatiCraft, ReikaKalseki; Botania, Vazkii
- 手册是否一定按照原文翻译？
- 手册翻译中，哪些梗/neta/meme是允许（或可以接受）的？
  - 推广：若原文即有meme，那么是否需要100%按照原文翻译？
  - 推广：若原文即有meme，但中文中无此meme/无对应的meme，则应如何处理？
- 不同格式的手册本地化文件是否应有互相独立的翻译指南（e.g. XML, JSON, Markdown）？
- 未完待续

**Comment by Krasjet** [comment]
大体来讲首先追求的都是原文，如果实在翻译不出来才可以尝试其它手段。

> 手册是否一定与教程画等号？

手册可以是mod作者对自己mod物品origin的一种阐述，或者增加mod的神秘感等，而不一定要求是对物品功能的阐述，这些东西完全可以交给第三方教程。

> 手册是否一定按照原文翻译？

参见大体原则。但汉化的前提是对条目所提物品的了解，并让对艺术加工手法的表达方式与原物品的真实功能兼容。

> 手册翻译中，哪些梗/neta/meme是允许（或可以接受）的？

中国人在中文下可以理解的，如果没法翻译的话则尝试用类似的手段改写，或直接直译，让玩家判断

> 不同格式的手册本地化文件是否应有互相独立的翻译指南（e.g. XML, JSON, Markdown）？

把保留字符串写好就行了，差别的只是格式的问题，翻译这一块都是统一的，并且这个也介绍不完，谁知道作者会自创什么新的格式

**Comment by AstonIceDog** [comment]
1.如果书本不分段落是否可以自行分段？

**Comment by Mrkwtkr** [comment]
中文与英文自动换行的区别在各种手册文件中还是比较常见和头疼的问题，这方面也可以纳入讨论

**Comment by 3TUSK** [comment]
换行一定是Mod作者的锅

**Comment by Krasjet** [comment]
自動換行衹是代碼里的bug啦，修復見這個，其它的懶得修啦/w\ https://github.com/TeamTotemic/Totemic/pull/18

**Comment by 3TUSK** [comment]
去reddit发一波贴就知道了

**Comment by AstonIceDog** [comment]
如果是用的Guide-API呢 @qianzha

**Comment by AstonIceDog** [comment]
2.guide.BloodArsenal.title=
guide.BloodArsenal.display=
guide.BloodArsenal.author=
guide.BloodArsenal.welcome=
是否要汉化？

**Comment by Krasjet** [comment]
@AstonIceDog 去先把这个看了 https://github.com/Meow-J/Mod-Translation-Styleguide

**Comment by AstonIceDog** [comment]
看过了

**Comment by AstonIceDog** [comment]
我看过了，我意思是书名，作者，display，欢迎语是否要翻译

**Comment by Krasjet** [comment]
> - 对于可以翻译的词，都需要翻译，除非有特殊的语境（如Botania的更新日志）
> - 指mod社区的某个人物，或贡献列表中的人物，则保留不翻译

**Comment by 3TUSK** [comment]
暂且先关闭。暂时没有别的疑问了。
