### ISSUE TITLE
关于Cyberware和Roots...

### ISSUE THREAD

**Issue by 3TUSK** [Meow-J/Mod-Translation-Styleguide#4]
从BTM16.2开始就一直关注的两个新MOD。但是个人认为它们的汉化者似乎对这两个MOD的名字有所误解...
- Cyberware: Cyber (of relating to mechanics, internet, tech, etc.) + ware (manufactured goods). 目前已知的搬运和汉化中的翻译是“机械战争”。不排除意译可能。~~但war != ware。~~参考：https://en.wikipedia.org/wiki/Cyberware
- Roots: 同字面意思，指植物的根须。同时暗指本MOD的基础魔法材料（Old root, 古老根须）。目前已知的搬运和汉化中的翻译是”起源魔法“。~~不排除意译可能。不排除误译可能。~~完全无解，选择死亡。

（因为学校WiFi疑似打不开gitter所以放这里来讨论了。）

**Comment by Krasjet** [comment]
Cyberware肯定不是战争啊

**Comment by Krasjet** [comment]
另外可以看一下这个：https://en.wikipedia.org/wiki/Cyberware

本意就为植入人体的机械器官，与人体已有神经系统建立联系

**Comment by 3TUSK** [comment]
所以看着心烦啊...Cyberware是怎么跟战争扯上直接关系的...我的第一反应是那个译者看漏了一个字母。

**Comment by Krasjet** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/17741079/8290c9ea-64cd-11e6-9044-89bac99ae519.png)
orz真是没救了

**Comment by 3TUSK** [comment]
~~没救了，贯彻Vigilantism的理念得了~~

**Comment by Krasjet** [comment]
@RainEffect

**Comment by 3TUSK** [comment]
@Meow-J Summoned wrong people. None of Roots translators are present on GitHub AFAIK.

Still considering about vigilantism.

**Comment by RainEffect** [comment]
<s>把我炸出来了...</s>
的确当时想着这个Cyberware模组的名称翻译的时候我的确想了一段时间。。。因为我根本不知道该怎么去翻译这个名字。。。目前这个“机械战争”的名字也只是我那边帮忙的一个小伙给起的名字。。。如果说不对的话求帮忙翻译一下。。。因为我已经想不到了。。。

**Comment by 3TUSK** [comment]
[赛伯格（Cyborg）](https://en.wikipedia.org/wiki/Cyborg)如何？——>没错我也想不到合适的名字

**Comment by RainEffect** [comment]
因为这个模组我是同步转载到mcbbs上的，相对而言这个模组的中文译名也算比较重要。因为对于玩家而言，名字才是这个模组给玩家带来的第一印象，所以我那时候就一直想不到。。。
顺便，<a href="https://en.wikipedia.org/wiki/Cyborg">赛伯格（Cyborg）</a>好像也是音译吧。。。

**Comment by 3TUSK** [comment]
总不可能译作“机甲战士”...吧...

> 引用中文维基百科：
> 改造人（英文：cyborg，又稱生化人、電子人、機械化人，音譯為賽博格）即是机械化有机体，是以无机物所构成的机器，作为有机体（包括人与其它动物在内）身体的一部分。通常这样做的目的是借由人工科技来增加或强化生物体的能力。

**Comment by RainEffect** [comment]
所以啊。。。名字我也是一直在考虑的，当时改了这名字之后我也其实有在想这个名字是不是有点歪曲了其原意。。。但是目前我也找不到一个相对正确的翻译。。。也没办法了。。。

**Comment by RainEffect** [comment]
目前如果换成“赛博格”的话。。。可以么？
或者还是说换成“机械化人”。。。因为我也实在不懂这个。。。
@3TUSK

**Comment by 3TUSK** [comment]
如果是我，我会选择让看贴的人投票...

**Comment by RainEffect** [comment]
这倒是个办法。。。我待会去发投票帖。。。

**Comment by TartaricAcid** [comment]
**Roots那个翻译是我的锅......**

> 那天直播时候有人问我：我打算把Roots翻译成自然魔法。
>    我当时说：这个mod主要是啥内容？
>    那人回复到：和古代的一些仪式有关。
>    我：Roots有起源的意思，叫起源魔法不更好么......

**......**

**Comment by Krasjet** [comment]
赛伯格 应该是更好一点的，Cyberware是技术，Cyborg是成品

**Comment by RainEffect** [comment]
我现在有点想哭了。。。[投票贴](http://www.mcbbs.net/thread-622655-1-1.html)现在简直感动死我。。。你们看看吧。。。我选择死亡。。。<img src="https://camo.githubusercontent.com/bdb9689746bc03b1b19119d26125bfa6efcfd6a7/687474703a2f2f7777772e6d636262732e6e65742f7374617469632f696d6167652f636f6d6d6f6e2f69636f6e5f6d656d6265722e676966" />

**Comment by Krasjet** [comment]
你要去解释一下机械战争的问题啊/w\

**Comment by RainEffect** [comment]
问题是我怎么解释(=/w\=)我不会说啦！

**Comment by Krasjet** [comment]
问题就是Cyberware这个单词以及mod内容都没有战争之意

**Comment by Krasjet** [comment]
另外应该在mod讨论版发啦，矿工茶馆本来就不是什么干正事的地方/w\

**Comment by RainEffect** [comment]
感谢出面帮忙(=/W\=)，大谢~
另，抱歉刚才家里停电了。。。现在才回电

**Comment by Na-moe** [comment]
关于roots，起源魔法我算是有一半听酒石酸的，另外一半是我自己觉得这译名挺好。
roots在魔法制作的方面大量使用图腾柱等物品，我觉得这种风格蛮像远古时期人们的祭祀行为。
我去征求过原作者意见，他or她说随我便，（甩锅意图明显（笑。
roots的俄文翻译则采取不译的形式。
或者叫根源魔法？主要我还是想让国内玩家一眼看出这是个魔法向mod。叫的太玄乎不太容易理解。
另外看起来roots要有大更新了，作者删了三个魔法想干啥？

**Comment by 3TUSK** [comment]
我只是想知道有没有别的翻译者有没有别的意见...

讲真的，我倾向于不翻译。
我总觉得Roots这里有双重含义，不论是“自然魔法”还是“起源魔法”都只能翻译出其中一重含义，不能两者兼顾...“根源魔法”可以兼顾但不太好听...

**Comment by Na-moe** [comment]
那我就无能为力了，在饭局上冥思苦想也没什么好点子，还是个人知识水平有限啊

**Comment by 3TUSK** [comment]
那就只能等那个HAYO的人的input了... - -
最后发现自己还是适合翻译科技类MOD - -

**Comment by TartaricAcid** [comment]
万物的起源不就是自然么，我的想法
【大雾】

**Comment by 3TUSK** [comment]
@Meow-J 总之我决定去解决换行问题了。
要不要把Botania的也修了？

**Comment by Krasjet** [comment]
其实我那种修法也会造成个小bug的/w\，如果使用语言中有用到空格的话

**Comment by 3TUSK** [comment]
使用语言有用到空格会发生什么？

**Comment by Krasjet** [comment]
一个词单独占一行

**Comment by RainEffect** [comment]
一个词一行。。。可以这很MC。。。用其他占行符例如'-'代替不行么？

**Comment by Krasjet** [comment]
不是啦，出现条件是后一个词非常长，像是德语这种才会出问题

**Comment by RainEffect** [comment]
那就实在没办法咯。。。只能改了。。。的确这样很麻烦的说。。。

**Comment by 3TUSK** [comment]
德语...我又想起了Vexatos
