### ISSUE TITLE
关于GT中一些物质的译名

### ISSUE THREAD

**Issue by ghost** [Meow-J/Mod-Translation-Styleguide#5]
在贴吧发过一个征求贴，但收效甚微，不得已来这提一下issue。  
[条目太多，这是链接](https://github.com/windstories/GregTech5EXP-ChineseLocalization/blob/master/Proper%20Nouns.md)  
希望各位有许多汉化经验的大大讨论并赐教一下，不胜感激。  
讨论结束后我会提交PR的。

**Comment by 3TUSK** [comment]
> Sulfuric Gas

~~疑似Mekansim？我去看一眼。~~
没有找到，看样子记错了。

**Comment by Krasjet** [comment]
Mekanism里面那个是硫酸的气体啦。

这里感觉应该是“硫化气”更好一点吧

这里的Sulfuric相对的是蒸馏之后的含硫产物，见https://git.io/v6PjO ，最后获得的是硫化的燃料Sulfuric Gas作为副产物，在之后的处理中燃料会有办法去硫化：https://git.io/v6Pju

上述所有有关的物质见这里：https://git.io/v6Pjf

**Comment by 3TUSK** [comment]
等等...我好像明白了什么

oilgc是[这个](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java#L361)，星系MOD的workaround。实际上和BC的oil等价。

我的猜想是这样的：

| English | 中文 |
| --- | --- |
| Sulfuric Gas | 含硫汽油 |
| Sulfuric Naphtha | 含硫石脑油 |
| Sulfuric Light Fuel | 含硫轻质燃油 |
| Sulfuric Heavy Fuel | 含硫重质燃油 |

（因为突然想起Gas也可以指Gasoline所以就这样猜了）

（[Hydric Sulfide怎么看都拼错了](https://en.wikipedia.org/wiki/Hydrogen_sulfide)，抑或这是溶于水的硫化氢？）

**Comment by 3TUSK** [comment]
> Teslatite

实际上是向某RedPower的蓝石致敬。类似的用法有Nikolite。（尼古拉.特斯拉天天中枪）
我建议统一按蓝石处理。但是这样做会导致遇到Bluestone这种合成词时没翻译可用。

**Comment by Krasjet** [comment]
不不不，Sulfuric Gas在代码里是个气体，而且颜色为(255,255,255,0)，即透明

**Comment by 3TUSK** [comment]
含硫汽油气

> WTF？

**Comment by 3TUSK** [comment]
Angmallen

[Metallurgy的神奇金属。](https://www.google.com/search?q=Angmallen)

顺手找到了[翻译](https://github.com/TeamMetallurgy/Metallurgy4/blob/master/src/main/resources/assets/metallurgy/lang/zh_CN.lang#L106)。

**Comment by Krasjet** [comment]
应该指的就是含有各种硫化物的气体，所以我想的是 硫化气

**Comment by Krasjet** [comment]
对了那个Osmonium，作者是想表达这个矿物非常轻而且快的

**Comment by 3TUSK** [comment]
我仍然倾向于[Gas是指汽油](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/preload/GT_Loader_Item_Block_And_Fluid.java#L403)。Refinery Gas不论怎么看都像是汽油啊...

**Comment by 3TUSK** [comment]
> Zectium

http://crazyores.wikia.com/wiki/Zectium_Ore
甚至我都没听说过有这个矿石...

**Comment by Krasjet** [comment]
上面那个[天然气](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/preload/GT_Loader_Item_Block_And_Fluid.java#L400)也是gas前缀啦

**Comment by 3TUSK** [comment]
> Fairy

疑似ExtraTiC的材料。  
来源：https://github.com/Glassmaker/ExtraTiC-Localization/blob/master/zh_CN.lang#L11

有汽油气这种东西？

**Comment by Krasjet** [comment]
而且你可以看这个方法名称：

> Materials.OilLight.**getFluid(150)**, new FluidStack[]{Materials.SulfuricGas.**getGas(240)**

**Comment by 3TUSK** [comment]
> Infuscolium

又是Metallurgy 4。[又是Metallurgy 4](https://github.com/TeamMetallurgy/Metallurgy4/blob/master/src/main/resources/assets/metallurgy/lang/zh_CN.lang#L207)。

**Comment by 3TUSK** [comment]
> Starconium

http://crazyores.wikia.com/wiki/Starconium_Ore
...?

**Comment by Krasjet** [comment]
> Zectium Ore: Zectium Ore needs diamond or better to be mined. When wearing a full set of zectium armor, you become **explosion proof**. Zectium cores can be thrown to **create giant explosions** but are only found in zectium dungeons. Zectium Protectors fly around these dungeons and shoot zectium cores when players near their treasures. There are also reinforced zectium blocks, windows, and chests.
> 
> Osmonium Ore: Osmonium Ore is known for **being light**, yet durable and needs tapazite or better to be mined. Osmonium tools are **extremely fast**, and are the second fastest tools in CrazyOres (Only the Starconium Sledgehammer is faster). When wearing a full set of Osmonium Armor, the player is given the ability to **walk at a faster pace**. Osmonium Golems also **walk much faster** than the normal golem. Osmonium can only be found above level 95 and is most common in hilly biomes.
> 
> Starconium Ore: Starconium Ore is the **rarest ore** found in the over world. It needs osmonium or better to be mined and is **very powerful**. A Starconium Sledgehammer can be created that is extremely **fast and strong**.

关键词都加粗了

**Comment by ghost** [comment]
万分感谢，其实这些wiki我都翻阅过，但各位大大的详细解释让我更透彻的理解。不过不得不吐槽冶金4的lang，自相矛盾呀！

> fluid.adamantine.molten=熔融金刚  
> 
> tile.metallurgy.adamantine.molten.name=熔融精金  
> 
> fluid.infuscolium.molten=熔融精金  
> 
> tile.metallurgy.infuscolium.molten.name=熔融魔金

**Comment by 3TUSK** [comment]
所以我很头疼啊...总感觉是我去年更新Metallurgy4的时候没注意...

**Comment by ghost** [comment]
~~列表已更新，至于3TUSK大大说的Hydric Sulfide的问题，我也很纳闷，难不成Blood Asp化学不好？~~  
~~（石化系统都写出来了，这么简单的错误会犯？）~~ 已经有人提issue了
~~至于那个蓝石的问题，个人认为还是加以区分一下比较好~~ 还是不区分了，估计和Forcicium AND Forcillium一个样子（这两个都翻译为力场晶体好了）  
此外还发现了一个重名的现象

> S:fluid.molten.infusedgold=熔融附魔金  
> 这和Infuscolium 是什么鬼？(╯‵□′)╯︵┻━┻

新增了一个待定条目
Igolashite--谷歌不到（干脆音译成伊格莱仕特算了，和那个伊格内休斯一样）  

此外针对Fairy，我又想到了Elvenelementium（貌似原来的翻译是什么第七元素，我改为了精灵源质，不知和Fairy冲不冲突？）

**Comment by ghost** [comment]
翻阅GTU的issues时发现了这个，简直和3TUSK想的一样。

> leagris commented 30 minutes ago
> When processing sulfuric fuels in a Chemical Reactor, it outputs Hydric Sulfid Cells with HS formula.
> 
> I think this is wrong, as this compound does not exists.
> 
> The real compound from natural gas and oil products is gaseous H2S that is toxic and smells like rotten eggs.
> 
> I'd suggest the following changes:
> 
> Keep the actual fluid
> Change its local name to Hydrogen Sulfide and tool-tip formula to H2S.
> Add an electrolyzer recipe to split H2 gas and Sulfur dust with:
> Input: 2×Hydrogen Sulfide Cells + 1×Empty Cell
> Output: 1 Hydrogen Cell + 1 Sulfur Dust
> Alt Input: 2000l Hydrogen Sulfide
> Alt output: 1000l Hydrogen + 1×Pile OF Sulfur Dust
> Anyway, the whole hydrogen gas stuff is wrong as it has formula H instead of H2.
> So if you don't want to fix the formula and name of current Hydric Sulfid, please add an electrolyzer recipe to split hydrogen and sulfur.

**Comment by Krasjet** [comment]
Hydric sulfide这个本来就是错的啊_(:з」∠)_，而且也没有人会说sulfuric gas这种东西的，至于原作者怎么想的不知道啦

**Comment by Krasjet** [comment]
那个Pokefennium不是指的是[Pokefenn](https://github.com/Pokefenn)吗

**Comment by ghost** [comment]
~~所以应该怎样翻译，音译吗?~~  
@Meow-J 其实这个汉化是在3TUSK给的ExtraTic的链接中找到的  

> fluid.pokefennium.molten=熔融铁血

**Comment by Krasjet** [comment]
见第四条啦 https://github.com/Meow-J/Mod-Translation-Styleguide

~~钅Pokefenn~~ Pokefenn金属 吧

**Comment by 3TUSK** [comment]
> 钅Pokefenn
> 23333333333333333333333333333333333

**Comment by Krasjet** [comment]
好像 Pokefenn合金 更好一点 /w\

**Comment by 3TUSK** [comment]
@TehporP

**Comment by TehporP** [comment]
我有点没搞懂你们在讨论什么...

**Comment by 3TUSK** [comment]
我们在讨论一些GT5U-Exp中的蛋疼物质名...有些是从GT5汉化问世以来就悬而未决的。
不知Tp有什么新想法？

**Comment by TehporP** [comment]
关于GAS的话 我倾向于气体这种说法 如果真的是要表达油这种玩意的话 不应该用oil这个么 那些生造的词我也没啥办法 毕竟才疏学浅..
Phoenixite 能直接看出来 Phoenix + ite 但是ite却是动词的词尾.. 要我说的话我估计会弄成凤凰元素？
Mercassium
Igolashite 
看不出
Starconium是出自于一个叫做[Crazy Ore](http://crazyores.wikia.com/wiki/Starconium_Ore)的mod 然而悲伤的是这个mod并没有被本地化

**Comment by 3TUSK** [comment]
因为在美国待得有点久，所以知道gas有时指gasoline（汽油）。
-ite一般是某种晶体的结尾。参考各种矿石。我想是“凤凰石”这样的。
Igolashite 疑似Metallurgy4。
Mercassium 疑似Metallurgy4。

**Comment by Krasjet** [comment]
关键是有这个啦：https://git.io/v6MWt

那几个带Gas的用的都是这个，其它甲烷，空气什么的也用的这个

**Comment by ghost** [comment]
Igolashite 原来给的翻译是伊格内休斯，但我发现这个条目译错了（伊格内休斯应该是Ignatius），于是这个条目就成无名氏了，连来源也查不到。
Mercassium 绝对不是Metallurgy4，语言文件都没有，我是在另一个太空4X游戏Aurora的wiki上找到的
