### ISSUE TITLE
关于UTF8

### ISSUE THREAD

**Issue by 3TUSK** [Meow-J/Mod-Translation-Styleguide#6]
如题。
有鉴于Windows依旧是主流的现状，UTF8的问题，以及换行的问题，其实是很难觉察到的吧...
也有一些MOD有这样诡异的情况。
是不是需要强调一下？

**Comment by Krasjet** [comment]
感觉换行其实没什么问题，原版语言文件用的就是Unix换行，至于手册什么的还是到游戏内自己测试啦。
