### ISSUE TITLE
关于标点...

### ISSUE THREAD

**Issue by 3TUSK** [Meow-J/Mod-Translation-Styleguide#8]
至今仍然有很多人用半角标点...理由不外乎就是全角标点不美观。 
没有办法Workaround吗？我隐隐觉得这个和FontRenderer或者某个字体图片有关...

**Comment by Krasjet** [comment]
问题是中文只和全角标点的显示效果是兼容的。

像是括号啦，中文不像英文是半角的，会比英文要宽很多，全角的括号能看得很清楚左右都是有空隙来（分离）的，这样才是正常的。而半角的则没有这种效果，这个是专门为拉丁字母表设计的，和中文放在一起会让内容(挤在)一起。而且，应该能看出来，半角括号会比较短一点，汉字的高度超出了括号，而全角的括号则没有这个问题。

这个可以看glyph的图像，注意两张图是一样大16*16的：
半角：
![default](https://cloud.githubusercontent.com/assets/5229241/19682894/41712a18-9ae2-11e6-939d-c51b1792a663.png)
全角：
![default](https://cloud.githubusercontent.com/assets/5229241/19682896/49346ab2-9ae2-11e6-8234-b67ba20a29e4.png)

另外是原版统一使用的是全角括号

**Comment by 3TUSK** [comment]
(昨晚的回复邮件根本没发出去）
所以说有没有必要把所有的半角标点全部换掉...？

**Comment by 3TUSK** [comment]
我主要是在意逗号……我的印象里句号、感叹号、问号没有问题，主要是分号、逗号……
还是说1.10.2里utc的glpyh更新了？

**Comment by Krasjet** [comment]
逗号分号问题更大啊/w\，半角的间距都不是为中文设计的

**Comment by 3TUSK** [comment]
但问题是现在的全角标点的视觉效果有问题。有部分标点根本没间距。
（你看到的邮件回复是十几个小时之前发的，喷）

**Comment by 3TUSK** [comment]
我个人是支持用全角标点的，但是我不记得1.10.2的实际效果是什么样的...

**Comment by 3TUSK** [comment]
已私信解释，疑似原版Glyph仍然有问题
