### ISSUE TITLE
是否可参考某些现有的中文文案排版指南

### ISSUE THREAD

**Issue by 3TUSK** [Meow-J/Mod-Translation-Styleguide#9]
昨天偶然发现了[这个](https://github.com/sparanoid/chinese-copywriting-guidelines)以及[这个](https://github.com/mzlogin/chinese-copywriting-guidelines)，我觉得还是很有参考价值的。

> 虽然我个人极其不习惯在中英混合排版时，用空格分隔英文和中文...

**Comment by Krasjet** [comment]
用空格分隔英文应该是正确的做法，但是在物品名字里好像就有点奇怪了

**Comment by Krasjet** [comment]
对了，看了下国家标准的排版，这个也是有用空格的：
![image](https://cloud.githubusercontent.com/assets/5229241/26022865/8a0fda60-37e2-11e7-8e3d-681607a7a5d5.png)
